openapi: 3.0.0
info:
  version: 1.0.0
  title: Sample API
  description: A sample API to illustrate OpenAPI concepts
paths:
  /:
    get:
      description: requests the index message
      responses:
        '200':
          description: Successfully got the index message
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IndexMessage'
        '400':
          $ref: '#/components/responses/400Error'
components:
  schemas:
    IndexMessage:
      type: object
      required:
        - value
      properties:
        value:
          type: string
  responses:
    400Error:
      description: Invalid request
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string